# Configuration of security hashes
---
development:
    common_password_salt: '28''(16(7%$$$)+1/+4.57-)6(508.5%3'
    
test:
    common_password_salt: '''))6616&,,/,002,%-#0%&""#$.*/81/'
    
production:
    common_password_salt: '7.8%''8&!3(''32-&,*-$2&"837)06+''68'